#!/usr/bin/php

<?php


use CronScheduler\CronSchedulerAddCommand;
use CronScheduler\CronSchedulerListCommand;
use CronScheduler\CronSchedulerLoadCommand;
use CronScheduler\XMLReader;
use Doctrine\ORM\EntityManager;
use Symfony\Component\Console\Application;

require_once __DIR__."/config/bootstrap.php";

$application = new Application();
$xmlReader = new XMLReader($lang);
$application->addCommands([
    new CronSchedulerLoadCommand($xmlReader,$em),
    new CronSchedulerListCommand($xmlReader,$em),
    new CronSchedulerAddCommand($xmlReader,$em,$baseFile)]);
$application->run();
