#!/usr/bin/php

<?php

require_once __DIR__."/config/bootstrap.php";

use CronScheduler\CronSchedulerAddCommand;
use CronScheduler\CronSchedulerListCommand;
use CronScheduler\CronSchedulerLoadCommand;
use Doctrine\ORM\EntityManager;
use Symfony\Component\Console\Application;
use Symfony\Component\DependencyInjection\ContainerBuilder;


$application = new Application();
/** @var ContainerBuilder $container */
$application->addCommands([
    new CronSchedulerLoadCommand($em),
    new CronSchedulerListCommand($em),
    new CronSchedulerAddCommand($em)]);
$application->run();
